### PR TITLE
🌱 Fix lint error

### PR DESCRIPTION
**Pull request by iurygregory**
The current code in BMO fails to build because of a missing import

Error: hostfirmwarecomponents_controller.go:132:6: undefined: errors (typecheck)

This commit fixes this issue.

### CODE REVIEW

**Comment by dtantsur** [comment]
/approve
/retitle 🌱 Fix lint error

(updating the title because it's not a user-visible fix)

**Comment by MahnoorAsghar** [comment]
lgtm :)

**Comment by tuminoid** [comment]
How was this even possible?

**Comment by dtantsur** [comment]
> How was this even possible?

My (unverified) assumption is that two PRs merged and broke each other.

**Comment by iurygregory** [comment]
> How was this even possible?

I only noticed after i did a rebase on my PR, after looking at the merged PRs I saw https://github.com/metal3-io/baremetal-operator/actions/runs/27339608752/job/80772701160 failed to build the BMO image 😅

**Comment by dtantsur** [comment]
Claude agrees:

Here's the full story — a **semantic merge conflict** that Git resolved textually but incorrectly.

**Three-way merge scenario for PR #3327:**

| Version                                     | `"errors"` import | Uses of `errors.Is()`                                                         |
| ------------------------------------------- | ----------------- | ----------------------------------------------------------------------------- |
| **Merge base** (ddc8c97)                    | Present           | Yes — `errors.Is(err, provisioner.ErrFirmwareUpdateUnsupported)` at line ~152 |
| **Main** (bef700c5a), after PR #3330 merged | **Removed**       | No — commit 6835bdbe removed both the import and the `errors.Is` call         |
| **Feature branch** (366ec768) for PR #3327  | Present           | Yes — **added a new** `errors.Is(err, provisioner.ErrNotReady)` at line 132   |

Git's three-way merge saw:
- Main **deleted** `"errors"` from the import block — take the deletion.
- Feature branch **added** new code using `errors.Is()` in a **different part of the file** (line 132 vs. the old line ~152) — take the addition.

No textual conflict. Git happily merged both changes: the import removal from main **and** the new usage from the feature branch. Result: `errors.Is()` called without importing `"errors"`.

**Why CI didn't catch it:** CI tests each PR against its own merge base. PR #3327's branch still had `import "errors"`, so it compiled fine. PR #3330's branch didn't use `errors.Is` anymore, so it also compiled fine. The breakage only exists in the **combination** of both changes, which was never tested. GitHub's merge happened automatically — no post-merge CI ran (or if it did, the result wasn't gating).

This is the classic "semantic merge conflict" problem. Git merges are textual, not semantic. The only defenses are post-merge CI (a `main` branch build after every merge) or a merge queue that serializes PRs and tests each one rebased on the latest main.

**Comment by 1nv0k32** [comment]
/lgtm
without power
Broke my build too, looking forward for merge :D

**Comment by 1nv0k32** [comment]
I guess merge trains would prevent such an issue :thinking:

**Review by tuminoid — COMMENTED** [review]
/lgtm
